name: run unit tests

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    name: Run unit tests

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.0"
      - name: Install dependencies and test with unittest
        run: |
          pip install -e .
          python -m unittest -v
